apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
spec:
  selector:
    matchLabels:
      name: airflow-webserver
  template:
    metadata:
      labels:
        name: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: airflow4corn:latest
          args: ["webserver"]
          env:
            - name: POSTGRES_HOST
              value: airflowdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgresadmin
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "0"
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "0"
            - name: AIRFLOW__API__AUTH_BACKEND
              value: airflow.api.auth.backend.default
            - name: FERNET_KEY
              value: L5Z7WRVv5zaexK0OL3pS2stYUF-gx_UmfDBqWQ4br6Y=
            - name: EXECUTOR
              value: Celery
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080