apiVersion: v1
kind: Service
metadata:
  name: airflow-svc
spec:
  type: NodePort
  selector:
    name: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: airflow-webserver-http
